all: dond spellpath

dond: dond.cpp
	g++ -g -std=c++98 -o dond dond.cpp

spellpath: spellpath.cpp
	g++ -g -std=c++98 -o spellpath spellpath.cpp

spellseeker: spellseeker.cpp
	g++ -g -std=c++98 -o spellseeker spellseeker.cpp

clean:
	rm dond spellpath spellseeker
